name: karmka_text_editor
description: Rich text editor for flutter based on work by Namhyun, Gu. Extended and made customizable for use in Karmka.
version: 0.0.2
author: Adam Bahr. Based on work by Namhyun, Gu
homepage: https://github.com/tutosirisom/karmka_text_editor

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter